Refinement
ViniciusPerillo/Trabalho-2-VC pull request #2
Opened 2024-09-11 01:02 UTC by jaymesakae

Nessa branch eu coloquei os arparses de download e caminho do dataset, além de dois parsers para experimentação no terminal.

README atualizado, mas talvez precise de algumas alterações posteriores

2024-09-11 17:09 UTC, tremefabris requested changes
comentei algumas alterações que acho necessárias

nada do que eu disse é regra, mas gostaria de pelo menos discutir os pontos que mencionei

2024-09-11 17:09 UTC, tremefabris commented on experiments.py
> +    ds = load_dataset(path, target_type="category", download=download)
aqui, o `target_type` tem que ser `"binary_category"` ao invés de `"category"`

2024-09-11 17:09 UTC, tremefabris commented on experiments.py
> +    ds = load_dataset(path, target_type="category", download=download)
e acho que o `download` podia ser tirado e colocado `True` -- se o professor colocar o dataset no `path`, ele automaticamente não vai fazer download, mas caso contrário ele faz sim

2024-09-11 17:09 UTC, tremefabris commented on experiments.py
> +    ds = load_dataset(path, target_type="category", download=download)
fazer a mesma coisa nesse `download`, ou seja, deixar como `True`

2024-09-11 17:09 UTC, tremefabris commented on experiments.py
> +    ds = load_dataset(path, target_type="category", download=download)
aqui, o `target_type` tá certo

2024-09-11 17:09 UTC, tremefabris commented on main.py
> +                    default=False, type=bool)
fico pensando que não precisa desse argumento `--download_dataset`, já que isso já é resolvido pelo downloader do pytorch

ou seja, se o `--dataset_path` que o fessô colocar já contém o dataset, ele não baixa; caso contrário, ele automaticamente baixa

então essa flag de `--download_dataset` me parece meio supérflua

2024-09-11 17:09 UTC, tremefabris commented on main.py
> +args = parser.parse_args()
mano, eu colocaria toda essa parte de argument parsing em um arquivo próprio chamado _args.py_, dentro de uma função (chamada, por exemplo, `parse_args`, mas tanto faz) e só importaria ela no _main.py_

2024-09-11 17:09 UTC, tremefabris commented on main.py
> +                    default=False, type=bool)
aqui eu acho que poderia ser diferente

ao invés de ter um bool em que `True == run_experiment` e `False == run_accuracy_experiment`, acho que poderia ter um valor `int`

tipo,
```
if args.experiment == 1:
    run_experiment(...)
elif args.experiment == 2:
    run_accuracy_experiment(...)
```

que que cê acha?

2024-09-11 17:09 UTC, tremefabris commented on main.py
> +                    default=None, nargs='+')
aqui, acho que o `nargs` teria que ser `2` ao invés de `'+'`

_tecnicamente_, poderia ser mais de 2, mas acho que uma boa parte dos experimentos vão quebrar se `len(prompts) > 2`

2024-09-11 17:09 UTC, tremefabris commented on main.py
> +                    default=None, nargs='+')
(e se pá deixar um `default` seria da hora tbm rs)

2024-09-11 17:09 UTC, tremefabris commented on utils.py
> +def load_dataset(path: Path = Path('./dataset/'), target_type: str = 'binary-category', download = False):
por mim, deixa `download = True`

2024-09-11 17:11 UTC, tremefabris reviewed
sobre os comentários na _main.py_...

2024-09-11 17:11 UTC, tremefabris commented on main.py
> -    # run_experiment(prompts)
eu deixaria esses comentários como forma de indicar pro fessô os prompts que ele mesmo pediu pro trabalho

2024-09-11 17:13 UTC, tremefabris commented on README.md
> +### Parametros do código
isso aqui talvez seria melhor pegar o próprio output do `python3 main.py --help` pra explicar a funcionalidade de cada coisa

de qualquer forma, pode ser ajeitado depois...

2024-09-11 17:14 UTC, tremefabris reviewed
pequenas mudanças

2024-09-11 17:14 UTC, tremefabris commented on README.md
> +```
e lembrar de, se a funcionalidade dos args forem alteradas, alterar aqui também

2024-09-11 21:23 UTC, jaymesakae commented on main.py
> +                    default=False, type=bool)
na proxima versao desse PR vai ta sem esse parser

2024-09-11 21:46 UTC, jaymesakae commented on main.py
> +                    default=False, type=bool)
eu pensei em mudar o prompt, tipo, por default, o prompt ta como None, e se fizer tipo
```bash
if prompt is None:
    run_experiment(...)
else:
    run_accuracy_experiment(..)
```

O que vc acha?

2024-09-11 21:59 UTC, jaymesakae commented on utils.py
> +def load_dataset(path: Path = Path('./dataset/'), target_type: str = 'binary-category', download = False):
tirando essa flag ou colocando como false, se n tem o dataset no path q foi mandado ele retorna erro, então vou tirar o parametro e deixar como default mesmo

2024-09-11 22:00 UTC, jaymesakae commented on main.py
> -    # run_experiment(prompts)
e se colocar eles como codigo executavel no proprio readme? faz sentido?

2024-09-12 00:18 UTC, jaymesakae commented on main.py
> +args = parser.parse_args()
eu não acho que tenha necessidade desse tópico por conta de que o arquivo main já esta bem enxuto e para que seja de mais facil visualização, é mais simples deixar neste mesmo arquivo

2024-09-13 14:13 UTC, tremefabris commented on main.py
> +args = parser.parse_args()
discordo mas aceito

2024-09-13 14:13 UTC, tremefabris commented on main.py
> -    # run_experiment(prompts)
pode ser também

2024-09-13 14:24 UTC, tremefabris approved these changes
parece bão

2024-09-13 14:26 UTC, tremefabris requested changes

2024-09-13 14:26 UTC, tremefabris commented on experiments.py
> +    prompts = [ f"A photo of a {c}" for c in class_names ]
mano, não era pra ter nada disso aqui não

o prompt que o fessô pediu pro experimento de acurácia é só "A photo of a {c}, a type of pet"

2024-09-13 14:26 UTC, tremefabris commented on experiments.py
> +    prompts = [ f"A photo of a {c}" for c in class_names ]
daria pra tirar toda essa segunda parte do `run_accuracy_experiment`

2024-09-13 14:27 UTC, tremefabris approved these changes

2024-09-13 14:27 UTC, tremefabris commented on experiments.py
> -    prompts = [ f"A photo of a {c}" for c in class_names ]
hmmmmm ok você já fez isso, beleza

2024-09-13 14:27 UTC, tremefabris commented on experiments.py
> -    prompts = [ f"A photo of a {c}" for c in class_names ]
esqueça tudo então

2024-09-13 14:38 UTC, merged